[dependencies]
unicode-segmentation = { version = "1.7.1", optional = true }
[features]
default = ["grapheme"]
grapheme = ["unicode-segmentation"]

[package]
edition = "2018"
name = "reverse_string"
version = "1.2.0"
